In [1]:
from mxnet import gluon, nd
from mxnet.gluon import nn

In [3]:
class CenteredLayer(nn.Block):
    def __init__(self, **kwargs):
        super(CenteredLayer, self).__init__(**kwargs)
    
    def forward(self, x):
        return x - x.mean()
layer = CenteredLayer()
layer(nd.array([1, 2, 3, 4, 5]))


[-2. -1.  0.  1.  2.]
<NDArray 5 @cpu(0)>

In [12]:
net = nn.Sequential()
net.add(nn.Dense(128),
       CenteredLayer())
net.initialize()
y = net(nd.random.uniform(shape=(4, 8)))
y.mean().asscalar()

3.929017e-10

In [14]:
params = gluon.ParameterDict()
params.get('param2', shape=(2, 3))
params

(
  Parameter param2 (shape=(2, 3), dtype=<class 'numpy.float32'>)
)

In [22]:
class MyDense(nn.Block):
    
    def __init__(self, units, in_units, **kwargs):
        super(MyDense, self).__init__(**kwargs)
        self.weight = self.params.get('weight', shape=(in_units, units))
        self.bias = self.params.get('bias', shape=(units,))
    
    def forward(self, x):
        linear = nd.dot(x, self.weight.data()) + self.bias.data()
        return nd.relu(linear)
dense = MyDense(units=3, in_units=5)
dense.params

mydense5_ (
  Parameter mydense5_weight (shape=(5, 3), dtype=<class 'numpy.float32'>)
  Parameter mydense5_bias (shape=(3,), dtype=<class 'numpy.float32'>)
)

In [19]:
dense.initialize()
dense(nd.random.uniform(shape=(2, 5)))


[[0.01951626 0.14137176 0.04375713]
 [0.         0.12300311 0.06732272]]
<NDArray 2x3 @cpu(0)>

In [64]:
net = nn.Sequential()
net.add(MyDense(8, in_units=64),
       MyDense(1, in_units=8))
net.initialize()
net(nd.random.uniform(shape=(2, 64)))


[[0.]
 [0.]]
<NDArray 2x1 @cpu(0)>